name: extramobs
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.13.2

workspace:
  - packages/mssql

dependencies:
  mssql: ^0.0.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  lints: ^6.0.0